# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/test_share',
                'doc_host': 'https://HasanGoni.github.io',
                'git_url': 'https://github.com/HasanGoni/test_share',
                'lib_path': 'test_share'},
  'syms': {'test_share.core': {'test_share.core.foo': ('core.html#foo', 'test_share/core.py')}}}
